import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 1. Import ReduxProvider mà bạn đã tạo ở thư mục redux
import { ReduxProvider } from "../redux/provider"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce App", // Có thể đổi lại tên Web ở đây cho ngầu nhé
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 2. Bọc ReduxProvider ở đây để toàn bộ các trang (children) đều dùng được Redux */}
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}